import sys
import os
import tempfile
import requests
import streamlit as st
from dotenv import load_dotenv

# Allow imports from the main project folder
sys.path.append(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

from services.document_formatter import format_docx, format_pdf

load_dotenv()

BACKEND_URL = os.getenv(
    "BACKEND_URL",
    "http://127.0.0.1:8000"
)

st.set_page_config(
    page_title="LegalEase",
    page_icon="⚖️",
    layout="wide"
)

st.title("⚖️ LegalEase")
st.subheader("AI-Powered Legal Document Generator")

st.warning(
    "This document is an AI-generated draft. "
    "Please review it with a qualified legal professional."
)

# -----------------------------
# Demo Mode
# -----------------------------

demo_mode = st.checkbox(
    "🎯 Demo Mode",
    help="Use this mode when Gemini API quota is unavailable."
)

document_type = st.selectbox(
    "Document Type",
    [
        "Employment Agreement",
        "Lease Agreement",
        "Non-Disclosure Agreement",
        "Service Agreement",
        "Other"
    ]
)

parties = st.text_area(
    "Parties",
    placeholder="Example: Employer: ABC Company; Employee: John Doe"
)

effective_date = st.date_input("Effective Date")

terms_text = st.text_area(
    "Key Terms",
    placeholder="Enter one term per line"
)

additional_instructions = st.text_area(
    "Additional Instructions",
    placeholder="Optional instructions"
)

# -----------------------------
# Generate button
# -----------------------------

if st.button("Generate Document", type="primary"):

    if not parties.strip():
        st.error("Please enter the parties.")
        st.stop()

    terms = [
        term.strip()
        for term in terms_text.splitlines()
        if term.strip()
    ]

    if not terms:
        st.error("Please enter at least one key term.")
        st.stop()

    # -----------------------------
    # DEMO DOCUMENT
    # -----------------------------

    if demo_mode:

        document = f"""
{document_type.upper()}

This document is a demonstration draft generated by LegalEase.

PARTIES

{parties}

EFFECTIVE DATE

{effective_date}

1. PURPOSE

This agreement sets out the general terms and conditions
between the parties identified above.

2. KEY TERMS

"""

        for index, term in enumerate(terms, start=1):
            document += f"{index}. {term}\n\n"

        document += """
3. CONFIDENTIALITY

The parties agree to maintain confidentiality of information
shared in connection with this agreement, where applicable.

4. GENERAL PROVISIONS

The parties acknowledge that this document is a draft prepared
for demonstration purposes and should be reviewed and modified
as necessary.

5. LEGAL REVIEW

This document is an AI-assisted draft and is not a substitute
for advice from a qualified legal professional.
"""

        st.success("Demo document generated successfully!")

    # -----------------------------
    # REAL GEMINI GENERATION
    # -----------------------------

    else:

        payload = {
            "document_type": document_type,
            "parties": parties,
            "terms": terms,
            "effective_date": str(effective_date),
            "additional_instructions": additional_instructions
        }

        try:

            with st.spinner(
                "Generating your legal document..."
            ):

                response = requests.post(
                    f"{BACKEND_URL}/generate",
                    json=payload,
                    timeout=120
                )

            if response.status_code == 200:

                data = response.json()
                document = data["content"]

                st.success(
                    "Document generated successfully!"
                )

            elif response.status_code == 429:

                st.error(
                    "Gemini API quota has been exceeded. "
                    "Enable Demo Mode to test the document "
                    "preview and download features."
                )

                st.stop()

            else:

                st.error(
                    f"Backend error: {response.status_code}"
                )

                st.code(response.text)

                st.stop()

        except requests.exceptions.RequestException as exc:

            st.error(
                f"Could not connect to backend: {exc}"
            )

            st.stop()

# -----------------------------
# Document Preview
# -----------------------------

if "document" in locals():

    st.subheader("📄 Document Preview")

    edited_document = st.text_area(
        "Edit your document",
        value=document,
        height=500
    )

    st.success(
        "You can edit the document before downloading."
    )

    # -----------------------------
    # Download files
    # -----------------------------

    st.subheader("⬇️ Download Document")

    # TXT
    st.download_button(
        "📄 Download TXT",
        data=edited_document,
        file_name="legalease_document.txt",
        mime="text/plain"
    )

    # Temporary DOCX and PDF
    with tempfile.TemporaryDirectory() as temp_dir:

        docx_path = os.path.join(
            temp_dir,
            "legalease_document.docx"
        )

        pdf_path = os.path.join(
            temp_dir,
            "legalease_document.pdf"
        )

        format_docx(
            edited_document,
            docx_path
        )

        format_pdf(
            edited_document,
            pdf_path
        )

        with open(docx_path, "rb") as f:
            docx_data = f.read()

        with open(pdf_path, "rb") as f:
            pdf_data = f.read()

    st.download_button(
        "📝 Download DOCX",
        data=docx_data,
        file_name="legalease_document.docx",
        mime=(
            "application/vnd.openxmlformats-officedocument."
            "wordprocessingml.document"
        )
    )

    st.download_button(
        "📕 Download PDF",
        data=pdf_data,
        file_name="legalease_document.pdf",
        mime="application/pdf"
    )