from pathlib import Path
import html
import re

from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

from fpdf import FPDF


def sanitize_text(text: str) -> str:
    """Clean text before exporting."""
    if not text:
        return ""

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    return text.strip()


def split_document(text: str) -> list[str]:
    """Split document into useful paragraphs."""
    text = sanitize_text(text)

    if not text:
        return []

    return [part.strip() for part in re.split(r"\n\s*\n", text) if part.strip()]


def format_html_preview(text: str) -> str:
    """Create HTML preview of the generated legal document."""

    text = sanitize_text(text)

    if not text:
        return "<p>No document generated.</p>"

    paragraphs = split_document(text)

    html_parts = []

    for paragraph in paragraphs:
        escaped = html.escape(paragraph)

        # Convert simple bullet points
        if paragraph.startswith(("-", "*", "•")):
            html_parts.append(
                f'<div style="margin-left:20px; margin-bottom:8px;">'
                f'{escaped}</div>'
            )
        else:
            html_parts.append(
                f'<p style="margin-bottom:12px; line-height:1.6;">'
                f'{escaped}</p>'
            )

    return "".join(html_parts)


def format_docx(text: str, output_path) -> str:
    """Create a formatted DOCX legal document."""

    text = sanitize_text(text)

    output_path = Path(output_path)

    document = Document()

    # Page margins
    section = document.sections[0]
    section.top_margin = Inches(0.75)
    section.bottom_margin = Inches(0.75)
    section.left_margin = Inches(0.85)
    section.right_margin = Inches(0.85)

    # Default font
    style = document.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(12)

    # Title
    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run("LEGALEASE")
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(18)

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = subtitle.add_run("AI-Powered Legal Document")
    run.italic = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(11)

    document.add_paragraph()

    # Document content
    paragraphs = split_document(text)

    for paragraph in paragraphs:
        p = document.add_paragraph()

        # Heading-like lines
        if (
            len(paragraph) < 100
            and paragraph.isupper()
        ):
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(paragraph)
            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(13)

        else:
            run = p.add_run(paragraph)
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)

    # Footer
    footer = section.footer
    footer_paragraph = footer.paragraphs[0]
    footer_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_run = footer_paragraph.add_run(
        "Generated by LegalEase - Please review with a qualified legal professional."
    )
    footer_run.font.name = "Times New Roman"
    footer_run.font.size = Pt(8)

    document.save(output_path)

    return str(output_path)


class LegalEasePDF(FPDF):
    """Custom PDF class for LegalEase."""

    def header(self):
        self.set_font("Times", "B", 14)
        self.cell(0, 10, "LEGALEASE", align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Times", "I", 8)
        self.cell(
            0,
            10,
            "Generated by LegalEase - Please review with a qualified legal professional.",
            align="C",
        )


def format_pdf(text: str, output_path) -> str:
    text = sanitize_text(text)

    # Convert unsupported Unicode characters to PDF-safe characters
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2026": "...",
        "\u2022": "-",
        "\u00a0": " ",
        "\u20b9": "INR",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    # Remove any remaining characters unsupported by the built-in Times font
    text = text.encode("latin-1", "replace").decode("latin-1")

    output_path = Path(output_path)

    pdf = LegalEasePDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_font("Times", "", 12)

    paragraphs = split_document(text)

    for paragraph in paragraphs:
        if len(paragraph) < 100 and paragraph.isupper():
            pdf.set_font("Times", "B", 13)
            pdf.multi_cell(0, 8, paragraph, align="C")
            pdf.ln(3)
            pdf.set_font("Times", "", 12)
        else:
            pdf.multi_cell(0, 7, paragraph)
            pdf.ln(3)

    pdf.output(str(output_path))

    return str(output_path)
    for paragraph in paragraphs:

        if len(paragraph) < 100 and paragraph.isupper():
            pdf.set_font("Times", "B", 13)
            pdf.multi_cell(0, 8, paragraph, align="C")
            pdf.ln(3)
            pdf.set_font("Times", "", 12)

        else:
            pdf.multi_cell(0, 7, paragraph)
            pdf.ln(3)

    pdf.output(str(output_path))

    return str(output_path)